/*
 * pix_recebimentos
 * APis Pix Recebimentos para Clientes (regulatórias). 
 *
 * OpenAPI spec version: 1.40.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.pedrocavalero.pix.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.pedrocavalero.pix.model.CobrancaPutRequestCalendario;
import com.pedrocavalero.pix.model.CobrancasDevedor;
import com.pedrocavalero.pix.model.CobrancasInfoAdicionais;
import com.pedrocavalero.pix.model.CobrancasValor;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * CobrancaPutRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-02-20T11:54:19.646-03:00")
public class CobrancaPutRequest {
  @JsonProperty("devedor")
  private CobrancasDevedor devedor = null;

  @JsonProperty("valor")
  private CobrancasValor valor = null;

  @JsonProperty("chave")
  private String chave = null;

  @JsonProperty("calendario")
  private CobrancaPutRequestCalendario calendario = null;

  @JsonProperty("infoAdicionais")
  private List<CobrancasInfoAdicionais> infoAdicionais = null;

  @JsonProperty("solicitacaoPagador")
  private String solicitacaoPagador = null;

  public CobrancaPutRequest devedor(CobrancasDevedor devedor) {
    this.devedor = devedor;
    return this;
  }

   /**
   * Get devedor
   * @return devedor
  **/
  @ApiModelProperty(value = "")
  public CobrancasDevedor getDevedor() {
    return devedor;
  }

  public void setDevedor(CobrancasDevedor devedor) {
    this.devedor = devedor;
  }

  public CobrancaPutRequest valor(CobrancasValor valor) {
    this.valor = valor;
    return this;
  }

   /**
   * Get valor
   * @return valor
  **/
  @ApiModelProperty(required = true, value = "")
  public CobrancasValor getValor() {
    return valor;
  }

  public void setValor(CobrancasValor valor) {
    this.valor = valor;
  }

  public CobrancaPutRequest chave(String chave) {
    this.chave = chave;
    return this;
  }

   /**
   * Chave Pix do Sistema DICT - BACEN
   * @return chave
  **/
  @ApiModelProperty(example = "a1f4102e-a446-4a57-bcce-6fa48899c1d1", required = true, value = "Chave Pix do Sistema DICT - BACEN")
  public String getChave() {
    return chave;
  }

  public void setChave(String chave) {
    this.chave = chave;
  }

  public CobrancaPutRequest calendario(CobrancaPutRequestCalendario calendario) {
    this.calendario = calendario;
    return this;
  }

   /**
   * Get calendario
   * @return calendario
  **/
  @ApiModelProperty(value = "")
  public CobrancaPutRequestCalendario getCalendario() {
    return calendario;
  }

  public void setCalendario(CobrancaPutRequestCalendario calendario) {
    this.calendario = calendario;
  }

  public CobrancaPutRequest infoAdicionais(List<CobrancasInfoAdicionais> infoAdicionais) {
    this.infoAdicionais = infoAdicionais;
    return this;
  }

  public CobrancaPutRequest addInfoAdicionaisItem(CobrancasInfoAdicionais infoAdicionaisItem) {
    if (this.infoAdicionais == null) {
      this.infoAdicionais = new ArrayList<CobrancasInfoAdicionais>();
    }
    this.infoAdicionais.add(infoAdicionaisItem);
    return this;
  }

   /**
   * Cada respectiva informação adicional contida na lista (nome e valor) deve ser apresentada ao pagador
   * @return infoAdicionais
  **/
  @ApiModelProperty(value = "Cada respectiva informação adicional contida na lista (nome e valor) deve ser apresentada ao pagador")
  public List<CobrancasInfoAdicionais> getInfoAdicionais() {
    return infoAdicionais;
  }

  public void setInfoAdicionais(List<CobrancasInfoAdicionais> infoAdicionais) {
    this.infoAdicionais = infoAdicionais;
  }

  public CobrancaPutRequest solicitacaoPagador(String solicitacaoPagador) {
    this.solicitacaoPagador = solicitacaoPagador;
    return this;
  }

   /**
   * O campo solicitacaoPagador, determina um texto a ser apresentado ao pagador para que ele possa digitar uma informação correlata, em formato livre, a ser enviada ao recebedor
   * @return solicitacaoPagador
  **/
  @ApiModelProperty(example = "Texto personalizado a ser apresentado ao pagador", value = "O campo solicitacaoPagador, determina um texto a ser apresentado ao pagador para que ele possa digitar uma informação correlata, em formato livre, a ser enviada ao recebedor")
  public String getSolicitacaoPagador() {
    return solicitacaoPagador;
  }

  public void setSolicitacaoPagador(String solicitacaoPagador) {
    this.solicitacaoPagador = solicitacaoPagador;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CobrancaPutRequest cobrancaPutRequest = (CobrancaPutRequest) o;
    return Objects.equals(this.devedor, cobrancaPutRequest.devedor) &&
        Objects.equals(this.valor, cobrancaPutRequest.valor) &&
        Objects.equals(this.chave, cobrancaPutRequest.chave) &&
        Objects.equals(this.calendario, cobrancaPutRequest.calendario) &&
        Objects.equals(this.infoAdicionais, cobrancaPutRequest.infoAdicionais) &&
        Objects.equals(this.solicitacaoPagador, cobrancaPutRequest.solicitacaoPagador);
  }

  @Override
  public int hashCode() {
    return Objects.hash(devedor, valor, chave, calendario, infoAdicionais, solicitacaoPagador);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CobrancaPutRequest {\n");
    
    sb.append("    devedor: ").append(toIndentedString(devedor)).append("\n");
    sb.append("    valor: ").append(toIndentedString(valor)).append("\n");
    sb.append("    chave: ").append(toIndentedString(chave)).append("\n");
    sb.append("    calendario: ").append(toIndentedString(calendario)).append("\n");
    sb.append("    infoAdicionais: ").append(toIndentedString(infoAdicionais)).append("\n");
    sb.append("    solicitacaoPagador: ").append(toIndentedString(solicitacaoPagador)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

