/*
 * pix_recebimentos
 * APis Pix Recebimentos para Clientes (regulatórias). 
 *
 * OpenAPI spec version: 1.40.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.pedrocavalero.pix.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.pedrocavalero.pix.model.CobrancasCobs;
import com.pedrocavalero.pix.model.CobrancasParametros;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * Cobrancas
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-02-20T11:54:19.646-03:00")
public class Cobrancas {
  @JsonProperty("cobs")
  private List<CobrancasCobs> cobs = new ArrayList<CobrancasCobs>();

  @JsonProperty("parametros")
  private CobrancasParametros parametros = null;

  public Cobrancas cobs(List<CobrancasCobs> cobs) {
    this.cobs = cobs;
    return this;
  }

  public Cobrancas addCobsItem(CobrancasCobs cobsItem) {
    this.cobs.add(cobsItem);
    return this;
  }

   /**
   * Estrutura com informações referentes a cobranca do documento
   * @return cobs
  **/
  @ApiModelProperty(required = true, value = "Estrutura com informações referentes a cobranca do documento")
  public List<CobrancasCobs> getCobs() {
    return cobs;
  }

  public void setCobs(List<CobrancasCobs> cobs) {
    this.cobs = cobs;
  }

  public Cobrancas parametros(CobrancasParametros parametros) {
    this.parametros = parametros;
    return this;
  }

   /**
   * Get parametros
   * @return parametros
  **/
  @ApiModelProperty(required = true, value = "")
  public CobrancasParametros getParametros() {
    return parametros;
  }

  public void setParametros(CobrancasParametros parametros) {
    this.parametros = parametros;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Cobrancas cobrancas = (Cobrancas) o;
    return Objects.equals(this.cobs, cobrancas.cobs) &&
        Objects.equals(this.parametros, cobrancas.parametros);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cobs, parametros);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Cobrancas {\n");
    
    sb.append("    cobs: ").append(toIndentedString(cobs)).append("\n");
    sb.append("    parametros: ").append(toIndentedString(parametros)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

