/*
 * pix_recebimentos
 * APis Pix Recebimentos para Clientes (regulatórias). 
 *
 * OpenAPI spec version: 1.40.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.pedrocavalero.pix.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.pedrocavalero.pix.model.CobrancasParametrosPaginacao;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * CobrancasParametros
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-02-20T11:54:19.646-03:00")
public class CobrancasParametros {
  @JsonProperty("paginacao")
  private CobrancasParametrosPaginacao paginacao = null;

  @JsonProperty("inicio")
  private String inicio = null;

  @JsonProperty("fim")
  private String fim = null;

  public CobrancasParametros paginacao(CobrancasParametrosPaginacao paginacao) {
    this.paginacao = paginacao;
    return this;
  }

   /**
   * Get paginacao
   * @return paginacao
  **/
  @ApiModelProperty(required = true, value = "")
  public CobrancasParametrosPaginacao getPaginacao() {
    return paginacao;
  }

  public void setPaginacao(CobrancasParametrosPaginacao paginacao) {
    this.paginacao = paginacao;
  }

  public CobrancasParametros inicio(String inicio) {
    this.inicio = inicio;
    return this;
  }

   /**
   * Data início da criação da cobrança, no formato &#39;2020-06-01T09:00&#39;.
   * @return inicio
  **/
  @ApiModelProperty(example = "2020-04-01T00:00:00Z", required = true, value = "Data início da criação da cobrança, no formato '2020-06-01T09:00'.")
  public String getInicio() {
    return inicio;
  }

  public void setInicio(String inicio) {
    this.inicio = inicio;
  }

  public CobrancasParametros fim(String fim) {
    this.fim = fim;
    return this;
  }

   /**
   * Data fim da criação da Cobrança, no formato &#39;2020-06-01T09:00&#39;.
   * @return fim
  **/
  @ApiModelProperty(example = "2020-04-01T23:59:59Z", required = true, value = "Data fim da criação da Cobrança, no formato '2020-06-01T09:00'.")
  public String getFim() {
    return fim;
  }

  public void setFim(String fim) {
    this.fim = fim;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CobrancasParametros cobrancasParametros = (CobrancasParametros) o;
    return Objects.equals(this.paginacao, cobrancasParametros.paginacao) &&
        Objects.equals(this.inicio, cobrancasParametros.inicio) &&
        Objects.equals(this.fim, cobrancasParametros.fim);
  }

  @Override
  public int hashCode() {
    return Objects.hash(paginacao, inicio, fim);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CobrancasParametros {\n");
    
    sb.append("    paginacao: ").append(toIndentedString(paginacao)).append("\n");
    sb.append("    inicio: ").append(toIndentedString(inicio)).append("\n");
    sb.append("    fim: ").append(toIndentedString(fim)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

