/*
 * pix_recebimentos
 * APis Pix Recebimentos para Clientes (regulatórias). 
 *
 * OpenAPI spec version: 1.40.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.pedrocavalero.pix.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.pedrocavalero.pix.model.CobrancaPutRequestCalendario;
import com.pedrocavalero.pix.model.CobrancasDevedor;
import com.pedrocavalero.pix.model.CobrancasInfoAdicionais;
import com.pedrocavalero.pix.model.CobrancasValor;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * CobrancaPatchRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-02-20T11:54:19.646-03:00")
public class CobrancaPatchRequest {
  @JsonProperty("devedor")
  private CobrancasDevedor devedor = null;

  @JsonProperty("valor")
  private CobrancasValor valor = null;

  @JsonProperty("calendario")
  private CobrancaPutRequestCalendario calendario = null;

  @JsonProperty("infoAdicionais")
  private List<CobrancasInfoAdicionais> infoAdicionais = null;

  @JsonProperty("solicitacaoPagador")
  private String solicitacaoPagador = null;

  @JsonProperty("status")
  private String status = null;

  public CobrancaPatchRequest devedor(CobrancasDevedor devedor) {
    this.devedor = devedor;
    return this;
  }

   /**
   * Get devedor
   * @return devedor
  **/
  @ApiModelProperty(value = "")
  public CobrancasDevedor getDevedor() {
    return devedor;
  }

  public void setDevedor(CobrancasDevedor devedor) {
    this.devedor = devedor;
  }

  public CobrancaPatchRequest valor(CobrancasValor valor) {
    this.valor = valor;
    return this;
  }

   /**
   * Get valor
   * @return valor
  **/
  @ApiModelProperty(value = "")
  public CobrancasValor getValor() {
    return valor;
  }

  public void setValor(CobrancasValor valor) {
    this.valor = valor;
  }

  public CobrancaPatchRequest calendario(CobrancaPutRequestCalendario calendario) {
    this.calendario = calendario;
    return this;
  }

   /**
   * Get calendario
   * @return calendario
  **/
  @ApiModelProperty(value = "")
  public CobrancaPutRequestCalendario getCalendario() {
    return calendario;
  }

  public void setCalendario(CobrancaPutRequestCalendario calendario) {
    this.calendario = calendario;
  }

  public CobrancaPatchRequest infoAdicionais(List<CobrancasInfoAdicionais> infoAdicionais) {
    this.infoAdicionais = infoAdicionais;
    return this;
  }

  public CobrancaPatchRequest addInfoAdicionaisItem(CobrancasInfoAdicionais infoAdicionaisItem) {
    if (this.infoAdicionais == null) {
      this.infoAdicionais = new ArrayList<CobrancasInfoAdicionais>();
    }
    this.infoAdicionais.add(infoAdicionaisItem);
    return this;
  }

   /**
   * Cada respectiva informação adicional contida na lista (nome e valor) deve ser apresentada ao pagador
   * @return infoAdicionais
  **/
  @ApiModelProperty(value = "Cada respectiva informação adicional contida na lista (nome e valor) deve ser apresentada ao pagador")
  public List<CobrancasInfoAdicionais> getInfoAdicionais() {
    return infoAdicionais;
  }

  public void setInfoAdicionais(List<CobrancasInfoAdicionais> infoAdicionais) {
    this.infoAdicionais = infoAdicionais;
  }

  public CobrancaPatchRequest solicitacaoPagador(String solicitacaoPagador) {
    this.solicitacaoPagador = solicitacaoPagador;
    return this;
  }

   /**
   * O campo solicitacaoPagador, determina um texto a ser apresentado ao pagador para que ele possa digitar uma informação correlata, em formato livre, a ser enviada ao recebedor
   * @return solicitacaoPagador
  **/
  @ApiModelProperty(example = "Texto personalizado a ser apresentado ao pagador", value = "O campo solicitacaoPagador, determina um texto a ser apresentado ao pagador para que ele possa digitar uma informação correlata, em formato livre, a ser enviada ao recebedor")
  public String getSolicitacaoPagador() {
    return solicitacaoPagador;
  }

  public void setSolicitacaoPagador(String solicitacaoPagador) {
    this.solicitacaoPagador = solicitacaoPagador;
  }

  public CobrancaPatchRequest status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Status da Cobrança
   * @return status
  **/
  @ApiModelProperty(example = "REMOVIDA_PELO_USUARIO_RECEBEDOR", value = "Status da Cobrança")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CobrancaPatchRequest cobrancaPatchRequest = (CobrancaPatchRequest) o;
    return Objects.equals(this.devedor, cobrancaPatchRequest.devedor) &&
        Objects.equals(this.valor, cobrancaPatchRequest.valor) &&
        Objects.equals(this.calendario, cobrancaPatchRequest.calendario) &&
        Objects.equals(this.infoAdicionais, cobrancaPatchRequest.infoAdicionais) &&
        Objects.equals(this.solicitacaoPagador, cobrancaPatchRequest.solicitacaoPagador) &&
        Objects.equals(this.status, cobrancaPatchRequest.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(devedor, valor, calendario, infoAdicionais, solicitacaoPagador, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CobrancaPatchRequest {\n");
    
    sb.append("    devedor: ").append(toIndentedString(devedor)).append("\n");
    sb.append("    valor: ").append(toIndentedString(valor)).append("\n");
    sb.append("    calendario: ").append(toIndentedString(calendario)).append("\n");
    sb.append("    infoAdicionais: ").append(toIndentedString(infoAdicionais)).append("\n");
    sb.append("    solicitacaoPagador: ").append(toIndentedString(solicitacaoPagador)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

