/*
 * pix_recebimentos
 * APis Pix Recebimentos para Clientes (regulatórias). 
 *
 * OpenAPI spec version: 1.40.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.pedrocavalero.pix.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * CobrancasInfoAdicionais
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-02-20T11:54:19.646-03:00")
public class CobrancasInfoAdicionais {
  @JsonProperty("valor")
  private String valor = null;

  @JsonProperty("nome")
  private String nome = null;

  public CobrancasInfoAdicionais valor(String valor) {
    this.valor = valor;
    return this;
  }

   /**
   * Valor ou dados à serem apresentados ao pagador.
   * @return valor
  **/
  @ApiModelProperty(example = "churrasco", required = true, value = "Valor ou dados à serem apresentados ao pagador.")
  public String getValor() {
    return valor;
  }

  public void setValor(String valor) {
    this.valor = valor;
  }

  public CobrancasInfoAdicionais nome(String nome) {
    this.nome = nome;
    return this;
  }

   /**
   * Nome do campo, que se queira dar a informação apresentada.
   * @return nome
  **/
  @ApiModelProperty(example = "Descricao complementar", required = true, value = "Nome do campo, que se queira dar a informação apresentada.")
  public String getNome() {
    return nome;
  }

  public void setNome(String nome) {
    this.nome = nome;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CobrancasInfoAdicionais cobrancasInfoAdicionais = (CobrancasInfoAdicionais) o;
    return Objects.equals(this.valor, cobrancasInfoAdicionais.valor) &&
        Objects.equals(this.nome, cobrancasInfoAdicionais.nome);
  }

  @Override
  public int hashCode() {
    return Objects.hash(valor, nome);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CobrancasInfoAdicionais {\n");
    
    sb.append("    valor: ").append(toIndentedString(valor)).append("\n");
    sb.append("    nome: ").append(toIndentedString(nome)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

