/*
 * pix_recebimentos
 * APis Pix Recebimentos para Clientes (regulatórias). 
 *
 * OpenAPI spec version: 1.40.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.pedrocavalero.pix.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Pagador, do qrcode pix, definido pelo emissor durante o cadastro
 */
@ApiModel(description = "Pagador, do qrcode pix, definido pelo emissor durante o cadastro")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-02-20T11:54:19.646-03:00")
public class PixsPagador {
  @JsonProperty("cpf")
  private String cpf = null;

  @JsonProperty("nome")
  private String nome = null;

  @JsonProperty("cnpj")
  private String cnpj = null;

  public PixsPagador cpf(String cpf) {
    this.cpf = cpf;
    return this;
  }

   /**
   * Número do Documento Cadastro de Pessoa Física. (Apenas CPF, não enviar CNPJ)
   * @return cpf
  **/
  @ApiModelProperty(example = "11111111111", required = true, value = "Número do Documento Cadastro de Pessoa Física. (Apenas CPF, não enviar CNPJ)")
  public String getCpf() {
    return cpf;
  }

  public void setCpf(String cpf) {
    this.cpf = cpf;
  }

  public PixsPagador nome(String nome) {
    this.nome = nome;
    return this;
  }

   /**
   * Nome do pagador da Cobrança. Necessário preencher o campo CNPJ ou o campo CPF. 
   * @return nome
  **/
  @ApiModelProperty(example = "Empresa de Serviços SA", required = true, value = "Nome do pagador da Cobrança. Necessário preencher o campo CNPJ ou o campo CPF. ")
  public String getNome() {
    return nome;
  }

  public void setNome(String nome) {
    this.nome = nome;
  }

  public PixsPagador cnpj(String cnpj) {
    this.cnpj = cnpj;
    return this;
  }

   /**
   * Número do Cadastro Nacional da Pessoa Jurídica. (Apenas CNPJ, não enviar CPF)
   * @return cnpj
  **/
  @ApiModelProperty(example = "12345678000195", required = true, value = "Número do Cadastro Nacional da Pessoa Jurídica. (Apenas CNPJ, não enviar CPF)")
  public String getCnpj() {
    return cnpj;
  }

  public void setCnpj(String cnpj) {
    this.cnpj = cnpj;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PixsPagador pixsPagador = (PixsPagador) o;
    return Objects.equals(this.cpf, pixsPagador.cpf) &&
        Objects.equals(this.nome, pixsPagador.nome) &&
        Objects.equals(this.cnpj, pixsPagador.cnpj);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cpf, nome, cnpj);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PixsPagador {\n");
    
    sb.append("    cpf: ").append(toIndentedString(cpf)).append("\n");
    sb.append("    nome: ").append(toIndentedString(nome)).append("\n");
    sb.append("    cnpj: ").append(toIndentedString(cnpj)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

