/*
 * pix_recebimentos
 * APis Pix Recebimentos para Clientes (regulatórias). 
 *
 * OpenAPI spec version: 1.40.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.pedrocavalero.pix.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.pedrocavalero.pix.model.PixsParametros;
import com.pedrocavalero.pix.model.PixsPix;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * Pixs
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-02-20T11:54:19.646-03:00")
public class Pixs {
  @JsonProperty("parametros")
  private PixsParametros parametros = null;

  @JsonProperty("pix")
  private List<PixsPix> pix = null;

  public Pixs parametros(PixsParametros parametros) {
    this.parametros = parametros;
    return this;
  }

   /**
   * Get parametros
   * @return parametros
  **/
  @ApiModelProperty(required = true, value = "")
  public PixsParametros getParametros() {
    return parametros;
  }

  public void setParametros(PixsParametros parametros) {
    this.parametros = parametros;
  }

  public Pixs pix(List<PixsPix> pix) {
    this.pix = pix;
    return this;
  }

  public Pixs addPixItem(PixsPix pixItem) {
    if (this.pix == null) {
      this.pix = new ArrayList<PixsPix>();
    }
    this.pix.add(pixItem);
    return this;
  }

   /**
   * Devolucoes registradas no documento
   * @return pix
  **/
  @ApiModelProperty(value = "Devolucoes registradas no documento")
  public List<PixsPix> getPix() {
    return pix;
  }

  public void setPix(List<PixsPix> pix) {
    this.pix = pix;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Pixs pixs = (Pixs) o;
    return Objects.equals(this.parametros, pixs.parametros) &&
        Objects.equals(this.pix, pixs.pix);
  }

  @Override
  public int hashCode() {
    return Objects.hash(parametros, pix);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Pixs {\n");
    
    sb.append("    parametros: ").append(toIndentedString(parametros)).append("\n");
    sb.append("    pix: ").append(toIndentedString(pix)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

