/*
 * pix_recebimentos
 * APis Pix Recebimentos para Clientes (regulatórias). 
 *
 * OpenAPI spec version: 1.40.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.pedrocavalero.pix.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Qrcode
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-02-20T11:54:19.646-03:00")
public class Qrcode {
  @JsonProperty("imagem_base64")
  private String imagemBase64 = null;

  @JsonProperty("pix_link")
  private String pixLink = null;

  @JsonProperty("emv")
  private String emv = null;

  public Qrcode imagemBase64(String imagemBase64) {
    this.imagemBase64 = imagemBase64;
    return this;
  }

   /**
   * Imagem em base64 do QRCODE PIX
   * @return imagemBase64
  **/
  @ApiModelProperty(example = "iVBORw0KGgoAAAANSUhEUgAAAPoAAAD6AQAAAACgl2eQAAAC3ElEQVR4Xu2XQW7kMAwEpY+I///FPkX6iLxVVJDxzCHYQ4Z7GcFwbKkCMGSz6bTr5/Wnve68rA9w1gc46wOc9W/AbK3vuNaOPTrX2i2Wm4XA4prheeuzQY2Y3c1KIF8Jk1tnm9fdz2YpMEfsWBxcZGm3Ef8B2I0CcUiqOMjU1QJcRIlYPJujk6rcLATU53pdr6p+Pf9lIJfNYq04IsgRX9tVwLRCMxRqa220MVqQt4SqALo2slto2qZ/2Mi+FQLTFOEZl62jcrGRZsyFwMY9kexEtF9G1s3e+BZMAcBJM0dcJ0vAYTMVAiQJlRCg/bpzuFw2sT/KAKRqfTgaVImz0FdvxSoAHKjLzjE7+ll3qjxMrADgDANVsSbMvtVHbkEWAEaJVEyOZTNV2b8eVQEaxwhd9HKULSfcMHmFgJ3Txfy8sVihhG7NWwCQHgS7jJAOppEN1F+rBAhnd3QSF7eTpCDSKASyb1VpRjuMkb1b41QAJok+cb57Yra6Y6YQ4Gyxv50kKjYFvLJgZcBlSMNJxgPAeZgPMy8AzE7Lubp8UMTG+yhWCUBiTA2jBdFSOhV7M5ACgCpZJEIUI0fpH2wWApcfdn7pYB49u9hvnuvRvAXAUq7aRjDLTJv3ZQLrAL6qsjI6iMnSzShWVAJskioLZWj7fOakgAoBYsTDESwe3q1aesi9ed8OoJBuWGHGwoRdKviWyfcDGQ83vrz7l6NTtvtf8X6AV1xjOdJ44uS07qN5CwB9W6Uq1CxWPt2CLAC2xrHyzu5SxUMz+y5WBXBaxWAbSQrH2VbBhQBVWQKONGbZpY08mXkB4EIfTekaKBkbz9P//YAREVbX1dUuM21oYd/FKgCUiBz56UZrgP3+sVcB4BsGeYqlVPpzsYqAedwb2ZixTN6jWEUABppDRBsFA9ye1wHJ2L328UrNAD9X881AVsaumYZIscJ/0u3pOuCn9QHO+gBnfYCzfgH4C2GVFDHlHIBpAAAAAElFTkSuQmCC", value = "Imagem em base64 do QRCODE PIX")
  public String getImagemBase64() {
    return imagemBase64;
  }

  public void setImagemBase64(String imagemBase64) {
    this.imagemBase64 = imagemBase64;
  }

  public Qrcode pixLink(String pixLink) {
    this.pixLink = pixLink;
    return this;
  }

   /**
   * URL do PIX para consulta do payload criptografado - Pix Link BACEN
   * @return pixLink
  **/
  @ApiModelProperty(example = "https://pix.bcb.gov.br/qr/MDAwMjAxMDEwMjEyMjY4NjAwMTRCUi5HT1YuQkNCLlBJWDI1NjRzcGktaC5pdGF1LmNvbS5ici9waXgvcXIvdjEvYzNkMTg5YjQtYzg1OS00MjE4LWI5ZGUtYjQ0NTk0NzU1YTJlNTIwNDAwMDA1MzAzOTg2NTgwMkJSNTkyNFBNRCBYQSBkYSBTaWx2YSBFaW5zdGVpbjYwMDlTQU8gUEFVTE82MjA3MDUwMyoqKjYzMDQ1RTY2", value = "URL do PIX para consulta do payload criptografado - Pix Link BACEN")
  public String getPixLink() {
    return pixLink;
  }

  public void setPixLink(String pixLink) {
    this.pixLink = pixLink;
  }

  public Qrcode emv(String emv) {
    this.emv = emv;
    return this;
  }

   /**
   * Texto do QR CODE no padrao EMVco
   * @return emv
  **/
  @ApiModelProperty(example = "00020101021226860014BR.GOV.BCB.PIX2564spi-h.itau.com.br/pix/qr/v1/c3d189b4-c859-4218-b9de-b44594755a2e5204000053039865802BR5924PMD XA da Silva Einstein6009SAO PAULO62070503***63045E66", value = "Texto do QR CODE no padrao EMVco")
  public String getEmv() {
    return emv;
  }

  public void setEmv(String emv) {
    this.emv = emv;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Qrcode qrcode = (Qrcode) o;
    return Objects.equals(this.imagemBase64, qrcode.imagemBase64) &&
        Objects.equals(this.pixLink, qrcode.pixLink) &&
        Objects.equals(this.emv, qrcode.emv);
  }

  @Override
  public int hashCode() {
    return Objects.hash(imagemBase64, pixLink, emv);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Qrcode {\n");
    
    sb.append("    imagemBase64: ").append(toIndentedString(imagemBase64)).append("\n");
    sb.append("    pixLink: ").append(toIndentedString(pixLink)).append("\n");
    sb.append("    emv: ").append(toIndentedString(emv)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

