/*
 * pix_recebimentos
 * APis Pix Recebimentos para Clientes (regulatórias). 
 *
 * OpenAPI spec version: 1.40.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.pedrocavalero.pix.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * WebhooksWebhooks
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-02-20T11:54:19.646-03:00")
public class WebhooksWebhooks {
  @JsonProperty("chave")
  private String chave = null;

  @JsonProperty("criacao")
  private String criacao = null;

  @JsonProperty("webhookUrl")
  private String webhookUrl = null;

  public WebhooksWebhooks chave(String chave) {
    this.chave = chave;
    return this;
  }

   /**
   * Chave de endereçamento do recebedor cadastrada na DICT
   * @return chave
  **/
  @ApiModelProperty(value = "Chave de endereçamento do recebedor cadastrada na DICT")
  public String getChave() {
    return chave;
  }

  public void setChave(String chave) {
    this.chave = chave;
  }

  public WebhooksWebhooks criacao(String criacao) {
    this.criacao = criacao;
    return this;
  }

   /**
   * Data e hora de criação do webhook em formato de acordo com RFC 3339
   * @return criacao
  **/
  @ApiModelProperty(value = "Data e hora de criação do webhook em formato de acordo com RFC 3339")
  public String getCriacao() {
    return criacao;
  }

  public void setCriacao(String criacao) {
    this.criacao = criacao;
  }

  public WebhooksWebhooks webhookUrl(String webhookUrl) {
    this.webhookUrl = webhookUrl;
    return this;
  }

   /**
   * URL para chamada webhook de aviso de recebimento pix
   * @return webhookUrl
  **/
  @ApiModelProperty(required = true, value = "URL para chamada webhook de aviso de recebimento pix")
  public String getWebhookUrl() {
    return webhookUrl;
  }

  public void setWebhookUrl(String webhookUrl) {
    this.webhookUrl = webhookUrl;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WebhooksWebhooks webhooksWebhooks = (WebhooksWebhooks) o;
    return Objects.equals(this.chave, webhooksWebhooks.chave) &&
        Objects.equals(this.criacao, webhooksWebhooks.criacao) &&
        Objects.equals(this.webhookUrl, webhooksWebhooks.webhookUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(chave, criacao, webhookUrl);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WebhooksWebhooks {\n");
    
    sb.append("    chave: ").append(toIndentedString(chave)).append("\n");
    sb.append("    criacao: ").append(toIndentedString(criacao)).append("\n");
    sb.append("    webhookUrl: ").append(toIndentedString(webhookUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

