/*
 * pix_recebimentos
 * APis Pix Recebimentos para Clientes (regulatórias). 
 *
 * OpenAPI spec version: 1.40.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.pedrocavalero.pix.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.pedrocavalero.pix.model.WebhooksParametros;
import com.pedrocavalero.pix.model.WebhooksWebhooks;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * Webhooks
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-02-20T11:54:19.646-03:00")
public class Webhooks {
  @JsonProperty("webhooks")
  private List<WebhooksWebhooks> webhooks = new ArrayList<WebhooksWebhooks>();

  @JsonProperty("parametros")
  private WebhooksParametros parametros = null;

  public Webhooks webhooks(List<WebhooksWebhooks> webhooks) {
    this.webhooks = webhooks;
    return this;
  }

  public Webhooks addWebhooksItem(WebhooksWebhooks webhooksItem) {
    this.webhooks.add(webhooksItem);
    return this;
  }

   /**
   * Webhooks cadastrados para o cliente
   * @return webhooks
  **/
  @ApiModelProperty(required = true, value = "Webhooks cadastrados para o cliente")
  public List<WebhooksWebhooks> getWebhooks() {
    return webhooks;
  }

  public void setWebhooks(List<WebhooksWebhooks> webhooks) {
    this.webhooks = webhooks;
  }

  public Webhooks parametros(WebhooksParametros parametros) {
    this.parametros = parametros;
    return this;
  }

   /**
   * Get parametros
   * @return parametros
  **/
  @ApiModelProperty(required = true, value = "")
  public WebhooksParametros getParametros() {
    return parametros;
  }

  public void setParametros(WebhooksParametros parametros) {
    this.parametros = parametros;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Webhooks webhooks = (Webhooks) o;
    return Objects.equals(this.webhooks, webhooks.webhooks) &&
        Objects.equals(this.parametros, webhooks.parametros);
  }

  @Override
  public int hashCode() {
    return Objects.hash(webhooks, parametros);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Webhooks {\n");
    
    sb.append("    webhooks: ").append(toIndentedString(webhooks)).append("\n");
    sb.append("    parametros: ").append(toIndentedString(parametros)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

