/*
 * API Pix
 * A API Pix padroniza serviços oferecidos pelo PSP recebedor no contexto do arranjo Pix, como criação de cobrança, verificação de Pix recebidos, devolução e conciliação. Os serviços expostos pelo PSP recebedor permitem ao usuário recebedor estabelecer integração de sua automação com os serviços PIX do PSP.  # Evolução da API Pix As seguintes mudanças são esperadas e consideradas retro-compatíveis (_backwards-compatibility_):  - Adição de novos recursos na API Pix. - Adição de novos parâmetros opcionais a cobranças. - Adição de novos campos em respostas da API Pix. - Alteração da ordem de campos. - Adição de novos elementos em enumerações  Mudanças compatíveis não geram nova versão da API Pix. Clientes devem estar preparados para lidar com essas mudanças sem quebrar.  Mudanças incompatíveis geram nova versão da API Pix.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: suporte.ti@bcb.gov.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.javaparainiciantes.boot.pix.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * CobCriacao
 */
@JsonPropertyOrder({
  CobCriacao.JSON_PROPERTY_CRIACAO
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-10-06T23:21:02.042427800-03:00[America/Sao_Paulo]")
public class CobCriacao {
  public static final String JSON_PROPERTY_CRIACAO = "criacao";
  private OffsetDateTime criacao;


  public CobCriacao criacao(OffsetDateTime criacao) {
    
    this.criacao = criacao;
    return this;
  }

   /**
   * Timestamp que indica o momento em que foi criada a cobrança. Respeita o formato definido na RFC 3339.
   * @return criacao
  **/
  @ApiModelProperty(required = true, value = "Timestamp que indica o momento em que foi criada a cobrança. Respeita o formato definido na RFC 3339.")
  @JsonProperty(JSON_PROPERTY_CRIACAO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getCriacao() {
    return criacao;
  }


  public void setCriacao(OffsetDateTime criacao) {
    this.criacao = criacao;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CobCriacao cobCriacao = (CobCriacao) o;
    return Objects.equals(this.criacao, cobCriacao.criacao);
  }

  @Override
  public int hashCode() {
    return Objects.hash(criacao);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CobCriacao {\n");
    sb.append("    criacao: ").append(toIndentedString(criacao)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

