/*
 * API Pix
 * A API Pix padroniza serviços oferecidos pelo PSP recebedor no contexto do arranjo Pix, como criação de cobrança, verificação de Pix recebidos, devolução e conciliação. Os serviços expostos pelo PSP recebedor permitem ao usuário recebedor estabelecer integração de sua automação com os serviços PIX do PSP.  # Evolução da API Pix As seguintes mudanças são esperadas e consideradas retro-compatíveis (_backwards-compatibility_):  - Adição de novos recursos na API Pix. - Adição de novos parâmetros opcionais a cobranças. - Adição de novos campos em respostas da API Pix. - Alteração da ordem de campos. - Adição de novos elementos em enumerações  Mudanças compatíveis não geram nova versão da API Pix. Clientes devem estar preparados para lidar com essas mudanças sem quebrar.  Mudanças incompatíveis geram nova versão da API Pix.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: suporte.ti@bcb.gov.br
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.javaparainiciantes.boot.pix.model;

import java.util.Objects;

import org.springframework.lang.Nullable;
import java.time.OffsetDateTime;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import io.swagger.annotations.ApiModelProperty;

/**
 * DevolucaoHorario
 */
@JsonPropertyOrder({
  DevolucaoHorario.JSON_PROPERTY_SOLICITACAO,
  DevolucaoHorario.JSON_PROPERTY_LIQUIDACAO
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-10-06T23:21:02.042427800-03:00[America/Sao_Paulo]")
public class DevolucaoHorario {
  public static final String JSON_PROPERTY_SOLICITACAO = "solicitacao";
  private OffsetDateTime solicitacao;

  public static final String JSON_PROPERTY_LIQUIDACAO = "liquidacao";
  private OffsetDateTime liquidacao;


  public DevolucaoHorario solicitacao(OffsetDateTime solicitacao) {
    
    this.solicitacao = solicitacao;
    return this;
  }

   /**
   * Horário no qual a devolução foi solicitada no PSP.
   * @return solicitacao
  **/
  @ApiModelProperty(required = true, value = "Horário no qual a devolução foi solicitada no PSP.")
  @JsonProperty(JSON_PROPERTY_SOLICITACAO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getSolicitacao() {
    return solicitacao;
  }


  public void setSolicitacao(OffsetDateTime solicitacao) {
    this.solicitacao = solicitacao;
  }


  public DevolucaoHorario liquidacao(OffsetDateTime liquidacao) {
    
    this.liquidacao = liquidacao;
    return this;
  }

   /**
   * Horário no qual a devolução foi liquidada no PSP.
   * @return liquidacao
  **/
  @Nullable
  @ApiModelProperty(value = "Horário no qual a devolução foi liquidada no PSP.")
  @JsonProperty(JSON_PROPERTY_LIQUIDACAO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getLiquidacao() {
    return liquidacao;
  }


  public void setLiquidacao(OffsetDateTime liquidacao) {
    this.liquidacao = liquidacao;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DevolucaoHorario devolucaoHorario = (DevolucaoHorario) o;
    return Objects.equals(this.solicitacao, devolucaoHorario.solicitacao) &&
        Objects.equals(this.liquidacao, devolucaoHorario.liquidacao);
  }

  @Override
  public int hashCode() {
    return Objects.hash(solicitacao, liquidacao);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DevolucaoHorario {\n");
    sb.append("    solicitacao: ").append(toIndentedString(solicitacao)).append("\n");
    sb.append("    liquidacao: ").append(toIndentedString(liquidacao)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

